#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace f1_seq.sv --exe f1_seq_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1_seq.mk Vf1_seq

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vf1_seq
echo "\nSimulation completed"

